import { Outfit } from "next/font/google";
import "./globals.css";
import Navbar from "@/component/Navbar";
import Footer from "@/component/Footer";
import SmoothScroll from "@/component/SmoosthScroll";

const OutFitFont = Outfit({
  subsets: ["latin"],
});

export const metadata = {
  title: "Pixgen",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${OutFitFont.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <SmoothScroll></SmoothScroll>
        <Navbar></Navbar>

        <main className='w-[90%] mx-auto'>{children}</main>
        
        <Footer></Footer>
        </body>
    </html>
  );
}
